apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SecurityProfilesOperatorDaemon
metadata:
  name: spod
  namespace: security-profiles-operator
spec:
  enableLogEnricher: true
  enableBpfRecorder: false
  hostProcVolumePath: /hostproc