name: CD
on:
  push:
jobs:
  dockerdesktop:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: kubernetes-sigs/security-profiles-operator
          path: security-profiles-operator
      - uses: docker-practice/actions-setup-docker@9fafeb38361d5d48e5afc207293715e023b6cfe0 # tag=1.0.9
      - run: brew install kind helm
      - run: |
          cd security-profiles-operator
          make image CONTAINER_RUNTIME=docker
          docker tag security-profiles-operator:latest localhost/security-profiles-operator:latest
      - run: ./run.sh
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: events.log
          path: events.log
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: sps.yaml
          path: sps.yaml
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: log-enricher.log
          path: log-enricher.log
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: bpf-recorder.log
          path: bpf-recorder.log
      # - name: Setup tmate session
      #   if: always()
      #   uses: mxschmitt/action-tmate@f309efdef7da88e388f96a3cafc4f181ac639f7a # renovate: tag=v3
      #   with:
      #     limit-access-to-actor: true

  podman:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: saschagrunert/security-profiles-operator
          ref: custom-host-proc
          path: security-profiles-operator
      - run: |
          brew install podman kind helm kubectl
          podman machine init --cpus=4 --memory=8096
          podman machine start
          podman system connection default podman-machine-default-root
      - run: |
          cd security-profiles-operator
          make image CONTAINER_RUNTIME=podman
          podman tag security-profiles-operator:latest localhost/security-profiles-operator:latest
      - run: ./run.sh
        env:  
          KIND_EXPERIMENTAL_PROVIDER: podman
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: events.log
          path: events.log
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: sps.yaml
          path: sps.yaml
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: log-enricher.log
          path: log-enricher.log
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: bpf-recorder.log
          path: bpf-recorder.log
      # - name: Setup tmate session
      #   if: always()
      #   uses: mxschmitt/action-tmate@f309efdef7da88e388f96a3cafc4f181ac639f7a # renovate: tag=v3
      #   with:
      #     limit-access-to-actor: true
