name: CD
on:
  push:
jobs:
  release-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@f309efdef7da88e388f96a3cafc4f181ac639f7a # renovate: tag=v3
      with:
        limit-access-to-actor: true